# Generated by Django 4.0.3 on 2022-04-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=16)),
                ('dateCreation', models.DateField()),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krach_achraf.client')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('numOperation', models.IntegerField(primary_key=True, serialize=False)),
                ('dateOperation', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=4)),
                ('typeOperation', models.CharField(choices=[('versement', 'versement'), ('retrait', 'retrait')], max_length=10)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krach_achraf.compte')),
            ],
        ),
    ]
