# Generated by Django 4.0.3 on 2022-04-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krach_achraf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
